name: running_shoe_mileage_log
description: A Flutter app to track running shoe mileage

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  http: ^1.2.0
  image_picker: ^1.0.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0
  file_picker: ^8.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true